/**
 * This class is generated by jOOQ
 */
package com.webonise.userCrud;


import com.webonise.userCrud.tables.Databasechangelog;
import com.webonise.userCrud.tables.Databasechangeloglock;
import com.webonise.userCrud.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in Users
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Users.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = com.webonise.userCrud.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>Users.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = com.webonise.userCrud.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>Users.user</code>.
     */
    public static final User USER = com.webonise.userCrud.tables.User.USER;
}
