/**
 * This class is generated by jOOQ
 */
package com.webonise.userCrud;


import com.webonise.userCrud.tables.Databasechangelog;
import com.webonise.userCrud.tables.Databasechangeloglock;
import com.webonise.userCrud.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends SchemaImpl {

    private static final long serialVersionUID = 1524081002;

    /**
     * The reference instance of <code>Users</code>
     */
    public static final Users USERS = new Users();

    /**
     * The table <code>Users.DATABASECHANGELOG</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = com.webonise.userCrud.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>Users.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = com.webonise.userCrud.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>Users.user</code>.
     */
    public final User USER = com.webonise.userCrud.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Users() {
        super("Users", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            User.USER);
    }
}
